name: chord
description: Predict HR deficiency from mutation contexts
keywords:
  - hrd
  - mutational signatures
tools:
  - chord:
      description: Prediction of HR deficiency from mutation contexts.
      homepage: https://github.com/UMCUGenetics/CHORD
      documentation: https://github.com/UMCUGenetics/CHORD
      licence: ["GPL v3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - smlv_vcf:
      type: file
      description: Tumor small variant VCF file
      pattern: "*.{vcf.gz}"
  - sv_vcf:
      type: file
      description: PURPLE SV VCF file
      pattern: "*.{vcf.gz}"
  - genome_fasta:
      type: file
      description: Reference genome assembly FASTA file
      pattern: "*.{fa,fasta}"
  - genome_fai:
      type: file
      description: Reference genome assembly fai file
      pattern: "*.{fai}"
  - genome_dict:
      type: file
      description: Reference genome assembly dict file
      pattern: "*.{dict}"
  - genome_ver:
      type: string
      description: Reference genome version
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - chord_dir:
      type: directory
      description: CHORD output directory
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
