name: bwa-mem2_mem_from_bam
description: The mem alignment algorithm of bwa-mem2, piping reads directly from BAM/CRAM files instead of FASTQ files
keywords:
  - bwa
  - mem
  - read alignment
  - bwa-mem2
tools:
  - bwa-mem2:
      description: Burrow-Wheeler Aligner for short-read alignment
      homepage: https://github.com/bwa-mem2/bwa-mem2
      documentation: https://github.com/bwa-mem2/bwa-mem2
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - bam_input:
        type: file
        description: Input coordinate-sorted BAM or CRAM to be realigned.
        pattern: "*.{bam,cram}"
  - genome_fasta:
      type: file
      description: Reference genome assembly FASTA file
      pattern: "*.{fa,fasta}"
  - genome_bwamem2_index:
      type: directory
      description: bwa-mem2 index directory
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - bam:
      type: list
      description: BAM and BAI file
      pattern: "*.{bam,bam.bai}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - command_files:
      type: list
      description: List of command files
authors:
  - "@scwatts"
  - "@mkcmkc"
  - "@oneillkza"
