name: "lilac_slice"
description: Slice BAM for LILAC
keywords:
  - samtools
  - slice
tools:
  - custom:
      description: "Slice BAM for LILAC"
      homepage: "https://github.com/umccr/hmftools"
      documentation: "https://github.com/umccr/hmftools"
      doi: ""
      licence: "['GPL v3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - bam:
      type: file
      description: BAM file
      pattern: "*.{bam}"
  - bai:
      type: file
      description: BAI file
      pattern: "*.{bai}"
  - bed:
      type: file
      description: Optional slice regions BED file
      pattern: "*.{bed}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - bam:
      type: file
      description: Sliced BAM file
      pattern: "*.{bam}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@scwatts"
