name: amber
description: Generate a tumor BAF file for PURPLE copy number fit
keywords:
  - baf
  - cnv
tools:
  - amber:
      description: Generate a tumor BAF file for PURPLE copy number fit.
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/amber
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/amber
      licence: ["GPL v3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id', tumor_id: 'tumor_name', normal_id: 'normal_name']
  - tumor_bam:
      type: file
      description: Tumor BAM file
      pattern: "*.{bam}"
  - normal_bam:
      type: file
      description: Normal BAM file
      pattern: "*.{bam}"
  - donor_bam:
      type: file
      description: Donor BAM file
      pattern: "*.{bam}"
  - tumor_bai:
      type: file
      description: Tumor BAI file
      pattern: "*.{bai}"
  - normal_bai:
      type: file
      description: Normal BAI file
      pattern: "*.{bai}"
  - donor_bai:
      type: file
      description: Donor BAI file
      pattern: "*.{bai}"
  - genome_ver:
      type: string
      description: Reference genome version
  - heterozygous_sites:
      type: file
      description: AMBER heterozygous sites file
      pattern: "*.{vcf.gz}"
  - target_region_bed:
      type: file
      description: Target region BED file (optional)
      pattern: "*.{bed}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id', tumor_id: 'tumor_name', normal_id: 'normal_name']
  - amber_dir:
      type: directory
      description: AMBER output directory
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
