name: "AMBER"
description: Generate a tumor BAF file for PURPLE copy number fit
keywords:
  - amber
  - baf
  - cnv
tools:
  - "AMBER":
      description: "Generate a tumor BAF file for PURPLE copy number fit."
      homepage: "https://github.com/hartwigmedical/hmftools/tree/master/amber"
      documentation: "https://github.com/hartwigmedical/hmftools/tree/master/amber"
      tool_dev_url: "https://github.com/hartwigmedical/hmftools/tree/master/amber"
      doi: ""
      licence: "['GPL v3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [['sample_name', 'tumor']: 'sample_tumor', [['sample_name', 'normal']]: 'sample_normal']
  - tumor_bam:
      type: file
      description: Tumor BAM file
      pattern: "*.{bam}"
  - normal_bam:
      type: file
      description: Normal BAM file
      pattern: "*.{bam}"
  - tumor_bai:
      type: file
      description: Tumor BAI file
      pattern: "*.{bai}"
  - normal_bai:
      type: file
      description: Normal BAI file
      pattern: "*.{bai}"
  - loci:
      type: file
      description: AMBER loci file
      pattern: "*.{vcf.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [['sample_name', 'tumor']: 'sample_tumor', [['sample_name', 'normal']]: 'sample_normal']
  - amber_dir:
      type: directory
      description: AMBER output directory
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@scwatts"
