lint:
  files_exist:
    - lib/Utils.groovy
    - lib/WorkflowMain.groovy
    - lib/WorkflowOncoanalyser.groovy
  files_unchanged:
    - assets/nf-core-oncoanalyser_logo_light.png
    - docs/images/nf-core-oncoanalyser_logo_dark.png
    - docs/images/nf-core-oncoanalyser_logo_light.png
  multiqc_config: false
  nextflow_config:
    - config_defaults:
        - params.fastp_umi_length
        - params.fastp_umi_skip
  nf_test_content: false
nf_core_version: 3.4.1
repository_type: pipeline
template:
  author: Stephen Watts
  description: A comprehensive cancer DNA/RNA analysis and reporting pipeline
  force: false
  is_nfcore: true
  name: oncoanalyser
  org: nf-core
  outdir: .
  skip_features:
    - gpu
    - nf-test
  version: 2.2.0dev
