lint:
  actions_ci: false
  files_exist:
    - lib/Utils.groovy
    - lib/WorkflowMain.groovy
    - lib/WorkflowOncoanalyser.groovy
  multiqc_config: false
  nextflow_config:
    - config_defaults:
        - params.fastp_umi_length
        - params.fastp_umi_skip
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Stephen Watts
  description: A comprehensive cancer DNA/RNA analysis and reporting pipeline
  force: false
  is_nfcore: true
  name: oncoanalyser
  org: nf-core
  outdir: .
  version: 1.1.0dev
