repository_type: pipeline
nf_core_version: 3.0.2
template:
  author: Stephen Watts
  description: A comprehensive cancer DNA/RNA analysis and reporting pipeline
  force: false
  is_nfcore: true
  name: oncoanalyser
  org: nf-core
  outdir: .
  skip_features: null
  version: 2.1.0dev
lint:
  actions_ci: False
  multiqc_config: False
  files_exist:
    - lib/Utils.groovy
    - lib/WorkflowMain.groovy
    - lib/WorkflowOncoanalyser.groovy
  files_unchanged:
    - assets/nf-core-oncoanalyser_logo_light.png
    - docs/images/nf-core-oncoanalyser_logo_dark.png
    - docs/images/nf-core-oncoanalyser_logo_light.png
  nextflow_config:
    - config_defaults:
        - params.fastp_umi_length
        - params.fastp_umi_skip
bump_version: null
org_path: null
update: null
