name: cobalt_panel_normalisation
description: Count bam lines determines the read depth ratios of the supplied tumor and reference genomes
keywords:
  - cobalt
  - read depth ratios
  - cnv
tools:
  - cobalt:
      description: Count bam lines determines the read depth ratios of the supplied tumor and reference genomes.
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/cobalt
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/cobalt
      licence:
        - GPL v3
input:
  - - amber_dir:
        type: list
        description: List of AMBER output directories
    - cobalt_dir:
        type: list
        description: List of COBALT output directories
  - - genome_ver:
        type: string
        description: Reference genome version
  - - gc_profile:
        type: file
        description: GC profile file
        pattern: '*.{cnp}'
  - - copy_number_percentiles:
        type: file
        description: Copy number percentiles file (optional)
  - - target_regions_bed:
        type: file
        description: Target regions BED file
        pattern: '*.{bed}'
output: {}
topics:
  cobalt_normalisation_tsv:
    - - cobalt.region_normalisation.*.tsv:
          type: file
          description: COBALT normalisation file
          pattern: cobalt.region_normalisation.*.tsv
  command_files:
    - - meta:
          type: map
          description: Empty map
      - identifier:
          type: string
          description: Identifier for command files
      - command_files:
          type: list
          description: List of command files
  versions:
    - - versions.yml:
          type: file
          description: File containing software versions
          pattern: versions.yml
authors:
  - '@scwatts'
