name: gridss_index
description: Create GRIDSS indices
keywords:
  - index
  - sv
tools:
  - gridss:
      description: GRIDSS is a module software suite containing tools useful for the detection of genomic rearrangements.
      homepage: https://github.com/PapenfussLab/gridss
      documentation: https://github.com/PapenfussLab/gridss
      licence: ["GPL >=3"]
input:
  - genome_fasta:
      type: file
      description: Reference genome assembly FASTA file
      pattern: "*.{fa,fasta}"
  - genome_fai:
      type: file
      description: Reference genome assembly fai file
      pattern: "*.{fai}"
  - genome_dict:
      type: file
      description: Reference genome assembly dict file (optional)
      pattern: "*.{dict}"
  - genome_bwa_index_dir:
      type: directory
      description: Directory containing reference genome assembly BWA index (optional)
  - genome_bwa_index_image:
      type: file
      description: Reference genome assembly BWA index img file (optional)
      pattern: "*.{img}"
  - indices:
      type: string
      description: List of indices to create
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - dict:
      type: file
      description: Reference genome dictionary file
      pattern: "*.{dict}"
  - img:
      type: file
      description: Reference genome BWA index image file
      pattern: "*.{img}"
  - index:
      type: file
      description: Reference genome GRIDSS index file
      pattern: "*.{gridsscache}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
