name: isofox
description: Characterise and count gene, transcript features
keywords:
  - rna
  - rnaseq
tools:
  - isofox:
      description: Characterises and counts gene, transcript features
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/isofox
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/isofox
      licence: ["GPL v3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - bam:
      type: file
      description: BAM file
      pattern: "*.{bam}"
  - bai:
      type: file
      description: BAI file
      pattern: "*.{bai}"
  - functions:
      type: string
      description: Isofox functions to run
  - read_length:
      type: integer
      description: Read length
  - genome_fasta:
      type: file
      description: Reference genome assembly FASTA file
      pattern: "*.{fa,fasta}"
  - genome_ver:
      type: string
      description: Reference genome version
  - genome_fai:
      type: file
      description: Reference genome assembly fai file
      pattern: "*.{fai}"
  - ensembl_data_resources:
      type: directory
      description: HMF ensembl data resources directory
  - exp_counts:
      type: file
      description: Isofox expected counts file (optional)
      pattern: "*.{csv}"
  - exp_gc_ratios:
      type: file
      description: Isofox expected GC ratio counts file (optional)
      pattern: "*.{csv}"
  - gene_ids:
      type: file
      description: Isofox gene ID file (optional)
      pattern: "*.{csv}"
  - tmp_norm:
      type: file
      description: Isofox TPM noramlisation file (optional)
      pattern: "*.{csv}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - isofox_dir:
      type: directory
      description: Isofox output directory
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
