name: cuppa_visualiser
description: Visualise tissue of origin predictions
keywords:
  - cup
  - tumor
  - classification
tools:
  - cuppa:
      description: Prediction of tumor sample tissue of origin
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/cuppa
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/cuppa
      licence: ["GPL v3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - csv:
      type: file
      description: CUPPA classification output file
      pattern: "*.{csv}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - conclusion:
      type: file
      description: Conclusion file
      pattern: "*.{txt}"
  - report:
      type: file
      description: Report PDF file
      pattern: "*.{pdf}"
  - summary_plot:
      type: file
      description: Summary plot file
      pattern: "*.{png}"
  - feature_plot:
      type: file
      description: Feature plot file
      pattern: "*.{png}"
  - chart_plot:
      type: file
      description: Chart plot file
      pattern: "*.{png}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
