name: qsee
description: Summarise key outputs of the HMF toolkit
keywords:
  - QC
  - quality control
  - metrics
tools:
  - orange:
      description: Calculates and visualises QC metrics
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/qsee
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/qsee
      licence:
        - GPL v3
input:
  - - meta:
        type: map
        description: |-
          Groovy Map containing sample information
          e.g. [tumor_id: 'tumor_id', normal_id: 'normal_id']
    - redux_tsvs_tumor:
        type: list
        description: REDUX tumor TSV files
    - redux_tsvs_normal:
        type: list
        description: REDUX normal TSV files (optional)
    - bamtools_dir_tumor:
        type: directory
        description: BamTools tumor output directory
    - bamtools_dir_normal:
        type: directory
        description: BamTools normal output directory (optional)
    - cobalt_dir:
        type: directory
        description: COBALT output directory (optional)
    - esvee_dir:
        type: directory
        description: ESVEE output directory (optional)
    - purple_dir:
        type: directory
        description: PURPLE output directory
  - - driver_gene_panel:
        type: file
        description: Driver gene panel file
        pattern: '*.{tsv}'
  - - cohort_percentiles:
        type: file
        description: HMF cohort percentiles file
        pattern: '*.{tsv}'
  - - sequencing_platform:
        type: string
        description: Sequencing platform
  - - targeted_mode:
        type: boolean
        description: Flag indicating whether targeted mode is set
output: {}
topics:
  qsee_dir:
    - - meta:
          type: map
          description: |-
            Groovy Map containing sample information
            e.g. [tumor_id: 'tumor_id', normal_id: 'normal_id']
      - qsee/:
          type: directory
          description: Qsee output directory
  command_files:
    - - meta:
          type: map
          description: |-
            Groovy Map containing sample information
            e.g. [tumor_id: 'tumor_id', normal_id: 'normal_id']
      - identifier:
          type: string
          description: Identifier for command files
      - command_files:
          type: list
          description: List of command files
  versions:
    - - versions.yml:
          type: file
          description: File containing software versions
          pattern: versions.yml
authors:
  - '@luan-n-nguyen'
