name: bwa-mem3_index
description: Create bwa-mem3 (bwa-mem2 format) index for reference genome
keywords:
  - index
  - fasta
  - genome
  - reference
tools:
  - bwa-mem3:
      description: |
        Short-read aligner derived from bwa-mem2 with correctness fixes and performance improvements
      homepage: https://github.com/fg-labs/bwa-mem3
      documentation: https://bwa-mem3.readthedocs.io
      licence: ["MIT"]
input:
  - fasta:
      type: file
      description: Input genome fasta file
  - alt:
      type: file
      description: Input genome ALT file (optional)
      pattern: "*.{alt}"
output:
  - bwamem3_index:
      type: file
      description: BWA genome index files (bwa-mem2 format)
      pattern: "*.{amb,ann,bwt.2bit.64,pac,alt}"
  - command_files:
      type: list
      description: List of command files
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@maxulysse"
maintainers:
  - "@maxulysse"
