name: pave_pon_creation
description: Annotate small variant VCF with gene, transcript coding and protein effects
keywords:
  - pave
  - annotation
  - gene
  - transcript
  - protein
  - vcf
tools:
  - pave:
      description: Annotates small variant VCF with gene, transcript coding and protein effects.
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/pave
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/pave
      licence: ["GPL v3"]
input:
  - sage_vcf:
      type: file
      description: SAGE VCF file
      pattern: "*.{vcf.gz}"
  - sage_tbi:
      type: file
      description: SAGE VCF index file
      pattern: "*.{tbi}"
  - genome_ver:
      type: string
      description: Reference genome version
output:
  - pave_artefacts:
      type: file
      description: PAVE artefacts file
      pattern: "*.{tsv}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - command_files:
      type: list
      description: List of command files
authors:
  - "@scwatts"
