contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #oncoanalyser channel"
    url: https://nfcore.slack.com/channels/oncoanalyser
    about: Discussion about the nf-core/oncoanalyser pipeline
