name: peach
description: Match germline small variants with pharmacogenetic evidence
keywords:
  - pharmacogenetic
  - variant
  - annotation
  - germline
tools:
  - peach:
      description: Matches germline small variants with pharmacogenetic evidence.
      homepage: https://github.com/hartwigmedical/peach
      documentation: https://github.com/hartwigmedical/peach
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id', tumor_id: 'tumor_name', normal_id: 'normal_name']
  - genome_ver:
      type: string
      description: Reference genome version
  - panel:
      type: file
      description: PEACH panel file
      pattern: "*.{json}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id', tumor_id: 'tumor_name', normal_id: 'normal_name']
  - genotype:
      type: file
      description: Genotypes file
      pattern: "*.{tsv}"
  - calls:
      type: file
      description: Haplotype calls file
      pattern: "*.{tsv}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
