name: "lilac_realign_reads_lilac"
description: Realign reads for LILAC
keywords:
  - alignment
  - lilac
  - preprocessing
tools:
  - custom:
      description: "Realign reads for LILAC"
      homepage: "https://github.com/umccr/hmftools"
      documentation: "https://github.com/umccr/hmftools"
      doi: ""
      licence: "['GPL v3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. ['id': 'sample_name']
  - bam:
      type: file
      description: BAM file
      pattern: "*.{bam}"
  - bai:
      type: file
      description: BAI file
      pattern: "*.{bai}"
  - reference:
      type: path
      description: Reference FASTA file
      pattern: "*.{fa}"
  - reference_indices:
      type: list
      description: BWA indices for reference FASTA file

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. ['id': 'sample_name']
  - bam:
      type: list
      description: BAM file
      pattern: "*.{bam}"
  - bai:
      type: list
      description: BAI file
      pattern: "*.{bai}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@scwatts"
