name: sambamba_merge
description: Merge several BAM files into one
keywords:
  - sambamba
  - bam
  - merge
tools:
  - sambamba:
      description: Tools for working with SAM/BAM data
      homepage: https://github.com/biod/sambamba
      documentation: https://lomereiter.github.io/sambamba/index.html
      licence: ["GPL v2"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id', tumor_id: 'tumor_name', normal_id: 'normal_name']
  - bams:
      type: list
      description: List BAM files
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id', tumor_id: 'tumor_name', normal_id: 'normal_name']
  - bam:
      type: file
      description: BAM file
      pattern: "*.{bam}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
  - "@mkcmkc"
