name: gripss_somatic
description: Filter and process GRIDSS somatic structural variants
keywords:
  - sv
  - filtering
  - somatic
tools:
  - gripss:
      description: Apply filtering and post-processing to GRIDSS structural variants.
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/gripss
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/gripss
      licence: ["GPL v3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id', tumor_id: 'tumor_name', normal_id: 'normal_name']
  - gridss_vcf:
      type: file
      description: VCF file
      pattern: "*.{vcf.gz}"
  - genome_fasta:
      type: file
      description: Reference genome assembly FASTA file
      pattern: "*.{fa,fasta}"
  - genome_ver:
      type: string
      description: Reference genome version
  - genome_fai:
      type: file
      description: Reference genome assembly fai file
      pattern: "*.{fai}"
  - pon_breakends:
      type: file
      description: GRIDSS breakend PON file
      pattern: "*.{bed.gz}"
  - pon_breakpoints:
      type: file
      description: GRIDSS breakpoint PON file
      pattern: "*.{bedpe.gz}"
  - known_fusions:
      type: file
      description: HMF Known Fusions file
      pattern: "*.{bedpe}"
  - repeatmasker_annotations:
      type: file
      description: RepeatMasker annotations file
  - target_region_bed:
      type: file
      description: Target region BED file (optional)
      pattern: "*.{bed}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id', tumor_id: 'tumor_name', normal_id: 'normal_name']
  - vcf:
      type: list
      description: Hard filtered VCF file and index file
      pattern: "*.{vcf.gz,vcf.gz.tbi}"
  - vcf_unfiltered:
      type: list
      description: Unfiltered VCF file and index file
      pattern: "*.{vcf.gz,vcf.gz.tbi}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
