name: gridss_assemble
description: Assemble SVs with GRIDSS
keywords:
  - assemble
  - sv
tools:
  - gridss:
      description: GRIDSS is a module software suite containing tools useful for the detection of genomic rearrangements.
      homepage: https://github.com/PapenfussLab/gridss
      documentation: https://github.com/PapenfussLab/gridss
      licence: ["GPL >=3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - bams:
      type: list
      description: List of BAM files
  - bams_filtered:
      type: list
      description: List of filtered BAM files
  - preprocess_dirs:
      type: list
      description: List of GRIDSS preprocess output directories
  - labels:
      type: list
      description: List of labels corresponding to BAMs and GRIDSS preprocess output directories
  - gridss_config:
      type: file
      description: GRIDSS configuration file (optional)
  - genome_fasta:
      type: file
      description: Reference genome assembly FASTA file
      pattern: "*.{fa,fasta}"
  - genome_fai:
      type: file
      description: Reference genome assembly fai file
      pattern: "*.{fai}"
  - genome_dict:
      type: file
      description: Reference genome assembly dict file
      pattern: "*.{dict}"
  - genome_gridss_index:
      type: file
      description: Reference genome assembly GRIDSS index file
      pattern: "*.{gridsscache}"
  - blocklist:
      type: file
      description: GRIDSS blocklist file
      pattern: "*.{bed.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - assembly_dir:
      type: directory
      description: GRIDSS assemble output directory
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
