name: "VISUALISER"
description: Visualise LINX somatic annotations
keywords:
  - linx
  - somatic
  - sv
  - annotation
  - visualisation
tools:
  - "LINX":
      description: "LINX is an annotation, interpretation and visualisation tool for structural variants."
      homepage: "https://github.com/hartwigmedical/hmftools/tree/master/linx"
      documentation: "https://github.com/hartwigmedical/hmftools/tree/master/linx"
      tool_dev_url: "https://github.com/hartwigmedical/hmftools/tree/master/linx"
      doi: ""
      licence: "['GPL v3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. ['subject_name': 'subject', ['sample_name', 'tumor']: 'sample', ['tumor', 'bam']: 'path/to/bam']
  - genome_ver:
      type: string
      description: Reference genome version
  - linx:
      type: directory
      description: LINX somatic annotation output directory
  - ensembl_data_dir:
      type: directory
      description: HMF Ensembl Data Cache directory

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. ['subject_name': 'subject', ['sample_name', 'tumor']: 'sample', ['tumor', 'bam']: 'path/to/bam']
  - visualiser_dir:
      type: directory
      description: LINX visualiser output directory
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@scwatts"
