name: linx_visualiser
description: Visualise LINX somatic annotations
keywords:
  - somatic
  - sv
  - annotation
  - visualisation
tools:
  - linx:
      description: An annotation, interpretation and visualisation tool for structural variants.
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/linx
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/linx
      licence: ["GPL v3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - linx_annotation_dir:
      type: directory
      description: LINX somatic annotation output directory
  - genome_ver:
      type: string
      description: Reference genome version
  - ensembl_data_resources:
      type: directory
      description: HMF ensembl data resources directory
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - plots:
      type: directory
      description: Directory containing output plots
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
