name: pave_somatic
description: Annotate small variant VCF with gene, transcript coding and protein effects
keywords:
  - pave
  - annotation
  - gene
  - transcript
  - protein
  - vcf
tools:
  - pave:
      description: Annotates small variant VCF with gene, transcript coding and protein effects.
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/pave
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/pave
      licence: ['GPL v3']
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - sage_vcf:
      type: file
      description: SAGE VCF file
      pattern: "*.{vcf.gz}"
  - genome_fasta:
      type: file
      description: Reference genome assembly fa file
      pattern: "*.{fa,fasta}"
  - genome_fai:
      type: file
      description: Reference genome assembly fai file
      pattern: "*.{fai}"
  - genome_ver:
      type: string
      description: Reference genome version
  - sage_pong:
      type: file
      description: SAGE PON file
      pattern: "*.{tsv.gz}"
  - segment_mappability:
      type: file
      description: Segment mappability file
      pattern: "*.{bed.gz}"
  - driver_gene_panel:
      type: file
      description: Driver gene panel file
      pattern: "*.{tsv}"
  - ensembl_data_resources:
      type: directory
      description: HMF ensembl data resources directory
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - vcf:
      type: file
      description: PAVE VCF file
      pattern: "*.{vcf.gz}"
  - index:
      type: file
      description: PAVE VCF index file
      pattern: "*.{vcf.gz.tbi}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
