name: "PREPROCESS"
description: Preprocess reads for GRIDSS
keywords:
  - gridss
  - read processing
  - sv
tools:
  - "gridss":
      description: "GRIDSS is a module software suite containing tools useful for the detection of genomic rearrangements."
      homepage: "https://github.com/PapenfussLab/gridss"
      documentation: "https://github.com/PapenfussLab/gridss"
      tool_dev_url: "https://github.com/PapenfussLab/gridss"
      doi: ""
      licence: "['GPL >=3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - bam:
      type: file
      description: BAM file
      pattern: "*.{bam}"
  - gridss_config:
      type: file
      description: Optional GRIDSS configuration file
  - genome_fa:
      type: file
      description: Reference genome assembly fa file
      pattern: "*.{fa,fasta}"
  - genome_fai:
      type: file
      description: Reference genome assembly fai file
      pattern: "*.{fai}"
  - genome_dict:
      type: file
      description: Reference genome assembly dict file
      pattern: "*.{dict}"
  - genome_bwa_index_dir:
      type: directory
      description: Directory containing reference genome assembly BWA index
  - genome_bwa_index_image:
      type: file
      description: Reference genome assembly BWA index img file
      pattern: "*.{img}"
  - genome_gridss_index:
      type: file
      description: Reference genome assembly GRIDSS index file
      pattern: "*.{gridsscache}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - preprocess_dir:
      type: directory
      description: GRIDSS preprocess output directory

authors:
  - "@scwatts"
