name: linx_germline
description: Generate LINX germline annotation data
keywords:
  - germline
  - sv
  - annotation
tools:
  - linx:
      description: An annotation, interpretation and visualisation tool for structural variants.
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/linx
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/linx
      licence: ["GPL v3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - sv_vcf:
      type: directory
      description: PURPLE germline SV VCF file
      pattern: "*.{vcf.gz}"
  - genome_ver:
      type: string
      description: Reference genome version
  - ensembl_data_resources:
      type: directory
      description: HMF ensembl data resources directory
  - driver_gene_panel:
      type: file
      description: Driver gene panel file
      pattern: "*.{tsv}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - annotation_dir:
      type: directory
      description: LINX annotation output directory
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
