name: "SVPREP"
description:
keywords:
  - svprep
  - filtering
tools:
  - "SVPREP":
      description: ""
      homepage: "https://github.com/hartwigmedical/hmftools/tree/master/sv-prep"
      documentation: "https://github.com/hartwigmedical/hmftools/tree/master/sv-prep"
      tool_dev_url: "https://github.com/hartwigmedical/hmftools/tree/master/sv-prep"
      doi: ""
      licence: "['GPL v3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample informatio
        e.g. [subject_name: 'subject', ['sample_name', 'tumor']: 'sample_tumor', ['sample_name', 'normal']: 'sample_normal']
  - tumor_bam:
      type: file
      description: Tumor BAM file
      pattern: "*.{bam}"
  - normal_bam:
      type: file
      description: Normal BAM file
      pattern: "*.{bam}"
  - tumor_bai:
      type: file
      description: Tumor BAI file
      pattern: "*.{bai}"
  - normal_bai:
      type: file
      description: Normal BAI file
      pattern: "*.{bai}"





  - genome_fa:
      type: file
      description: Reference genome assembly fa file
      pattern: "*.{fa,fasta}"
  - genome_fai:
      type: file
      description: Reference genome assembly fai file
      pattern: "*.{fai}"
  - genome_dict:
      type: file
      description: Reference genome assembly dict file
      pattern: "*.{dict}"
  - genome_ver:
      type: string
      description: Reference genome version
  - ensembl_data_dir:
      type: directory
      description: HMF Ensembl Data Cache directory
      pattern: "*.{tsv}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [subject_name: 'subject', ['sample_name', 'tumor']: 'sample_tumor', ['sample_name', 'normal']: 'sample_normal']
  - vcf:
      type: file
      description: SAGE VCF file
      pattern: "*.{vcf.gz}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@scwatts"
