name: linx_somatic
description: Generate LINX somatic annotation data
keywords:
  - somatic
  - sv
  - annotation
tools:
  - linx:
      description: An annotation, interpretation and visualisation tool for structural variants.
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/linx
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/linx
      licence: ["GPL v3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - purple_dir:
      type: directory
      description: PURPLE output directory
  - genome_ver:
      type: string
      description: Reference genome version
  - ensembl_data_resources:
      type: directory
      description: HMF ensembl data resources directory
  - known_fusion_data:
      type: file
      description: Known fusions data file
      pattern: "*.{bedpe}"
  - driver_gene_panel:
      type: file
      description: Driver Gene Panel file
      pattern: "*.{csv}"
  - gene_id_file:
      type: file
      description: Ensembl gene ID file (optional)
      pattern: "*.{csv}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - annotation_dir:
      type: directory
      description: LINX annotation output directory
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
