name: esvee_call
description: Call somatic SVs with ESVEE
keywords:
  - calling
  - sv
tools:
  - esvee:
      description: Structural variant (SV) calling
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/esvee
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/esvee
      licence: ["GPL >=3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - ref_depth_vcf:
      type: file
      description: ESVEE depth annotated VCF file
      pattern: "*.{vcf.gz}"
  - prep_dir:
      type: directory
      description: ESVEE prep output directory
  - genome_fasta:
      type: file
      description: Reference genome assembly FASTA file
      pattern: "*.{fa,fasta}"
  - genome_ver:
      type: string
      description: Reference genome version
  - pon_breakend:
      type: file
      description: GRIDSS breakend PON file
      pattern: "*.{bed.gz}"
  - pon_breakpoints:
      type: file
      description: GRIDSS breakpoint PON file
      pattern: "*.{bedpe.gz}"
  - known_fusions:
      type: file
      description: HMF Known Fusions file
      pattern: "*.{bedpe}"
  - repeatmasker_annotations:
      type: file
      description: RepeatMasker annotations file
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - caller_dir:
      type: directory
      description: ESVEE call output directory
  - unfiltered_vcf:
      type: list
      description: Unfiltered VCF file
      pattern: "*.{vcf.gz,vcf.gz.tbi}"
  - somatic_vcf:
      type: list
      description: Somatic VCF file
      pattern: "*.{vcf.gz,vcf.gz.tbi}"
  - germline_vcf:
      type: list
      description: Germline VCF file (optional)
      pattern: "*.{vcf.gz,vcf.gz.tbi}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
