name: esvee_call
description: Call somatic SVs with ESVEE
keywords:
  - calling
  - sv
tools:
  - esvee:
      description: Structural variant (SV) calling
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/esvee
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/esvee
      licence: ["GPL >=3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - bams:
      type: list
      description: List of BAM files
  - bams_filtered:
      type: list
      description: List of filtered BAM files
  - assemble_dir:
      type: directory
      description: GRIDSS assemble output directory
  - labels:
      type: list
      description: List of labels corresponding to BAMs and GRIDSS preprocess output directories
  - genome_fasta:
      type: file
      description: Reference genome assembly FASTA file
      pattern: "*.{fa,fasta}"
  - genome_fai:
      type: file
      description: Reference genome assembly fai file
      pattern: "*.{fai}"
  - genome_dict:
      type: file
      description: Reference genome assembly dict file
      pattern: "*.{dict}"
  - genome_gridss_index:
      type: file
      description: Reference genome assembly GRIDSS index file
      pattern: "*.{gridsscache}"
  - blocklist:
      type: file
      description: GRIDSS blocklist file
      pattern: "*.{bed.gz}"
  - gridss_config:
      type: file
      description: GRIDSS configuration file (optional)
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - vcf:
      type: file
      description: VCF file
      pattern: "*.{vcf.gz}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
