name: isofox_panel_normalisation
description: Characterise and count gene, transcript features
keywords:
  - rna
  - rnaseq
tools:
  - isofox:
      description: Characterises and counts gene, transcript features
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/isofox
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/isofox
      licence: ["GPL v3"]
input:
  - isofox_dirs:
      type: directory
      description: List of Isofox directories
  - genome_ver:
      type: string
      description: Reference genome version
  - gene_ids:
      type: file
      description: Isofox gene ID file (optional)
      pattern: "*.{csv}"
  - gene_distribution:
      type: file
      description: Isofox cohort gene expression file
      pattern: "*.{csv}"
output:
  - isofox_normalisation:
      type: file
      description: Isofox normalisation file
      pattern: "versions.yml"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
