name: cuppa_classifier
description: Predict tumor sample tissue of origin
keywords:
  - cup
  - tumor
  - classification
tools:
  - cuppa:
      description: Prediction of tumor sample tissue of origin
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/cuppa
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/cuppa
      licence: ["GPL v3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - isofox_dir:
      type: directory
      description: Isofox output directory (optional)
  - purple_dir:
      type: directory
      description: PURPLE output directory (optional)
  - linx_dir:
      type: directory
      description: LINX output directory (optional)
  - virusinterpreter:
      type: file
      description: Virus Interpreter annotations file (optional)
      pattern: "*.{tsv}"
  - cuppa_resources:
      type: directory
      description: CUPPA resource directory
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - csv:
      type: file
      description: CUPPA classification output file
      pattern: "*.{csv}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
