name: protect
description: Match somatic variants with treatment evidence
keywords:
  - treatment
  - variant
  - annotation
  - somatic
tools:
  - protect:
      description: Matches somatic variants with treatment evidence.
      homepage: https://github.com/hartwigmedical/oncoact/tree/master/protect
      documentation: https://github.com/hartwigmedical/oncoact/tree/master/protect
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id', tumor_id: 'tumor_name', normal_id: 'normal_name']
  - chord_prediction:
      type: file
      description: CHORD prediction file
      pattern: "*.{txt}"
  - purple_dir:
      type: directory
      description: PURPLE output directory
  - linx_dir:
      type: directory
      description: LINX somatic annotation output directory
  - lilac_dir:
      type: directory
      description: LILAC output directory
  - virusinterpreter:
      type: file
      description: Virus Interpreter annotations file
      pattern: "*.{tsv}"
  - genome_ver:
      type: string
      description: Reference genome version
  - serve_resources:
      type: directory
      description: SERVE resources directory
  - disease_ontology:
      type: file
      description: Disease ontology file
      pattern: "*.{json}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id', tumor_id: 'tumor_name', normal_id: 'normal_name']
  - tsv:
      type: file
      description: PROTECT output file
      pattern: "*.{tsv}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
