name: esvee_depth_annotator
description: Annotate ESVEE VCFs with depth information
keywords:
  - depth
  - annotation
  - sv
tools:
  - esvee:
      description: Structural variant (SV) calling
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/esvee
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/esvee
      licence: ["GPL >=3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - bams:
      type: list
      description: BAM files
  - bai:
      type: list
      description: BAI files
  - vcf:
      type: file
      description: VCF file
      pattern: "*.{vcf.gz}"
  - labels:
      type: list
      description: List of labels corresponding to BAMs and GRIDSS preprocess output directories
  - genome_fasta:
      type: file
      description: Reference genome assembly FASTA file
      pattern: "*.{fa,fasta}"
  - genome_ver:
      type: string
      description: Reference genome version
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - vcf:
      type: file
      description: VCF file
      pattern: "*.{vcf.gz}"
  - tbi:
      type: file
      description: VCF index file
      pattern: "*.{vcf.gz.tbi}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@scwatts"
