name: sage_somatic
description: A precise and highly sensitive somatic SNV, MNV and small INDEL caller
keywords:
  - somatic
  - variant caller
  - snv
  - mnv
tools:
  - sage:
      description: A precise and highly sensitive somatic SNV, MNV and small INDEL caller.
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/sage
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/sage
      licence: ["GPL v3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample informatio
        e.g. [id: 'sample_id']
  - tumor_bam:
      type: file
      description: Tumor BAM file
      pattern: "*.{bam}"
  - normal_bam:
      type: file
      description: Normal BAM file
      pattern: "*.{bam}"
  - donor_bam:
      type: file
      description: Donor BAM file
      pattern: "*.{bam}"
  - tumor_bai:
      type: file
      description: Tumor BAI file
      pattern: "*.{bai}"
  - normal_bai:
      type: file
      description: Normal BAI file
      pattern: "*.{bai}"
  - donor_bai:
      type: file
      description: Donor BAI file
      pattern: "*.{bai}"
  - redux_tsvs:
      type: list
      description: REDUX MS files
  - genome_fasta:
      type: file
      description: Reference genome assembly FASTA file
      pattern: "*.{fa,fasta}"
  - genome_ver:
      type: string
      description: Reference genome version
  - genome_fai:
      type: file
      description: Reference genome assembly fai file
      pattern: "*.{fai}"
  - genome_dict:
      type: file
      description: Reference genome assembly dict file
      pattern: "*.{dict}"
  - sage_pon:
      type: file
      description: SAGE PON file (optional)
      pattern: "*.{tsv.gz}"
  - sage_known_hotspots_somatic:
      type: file
      description: SAGE somatic known hotspots file
      pattern: "*.{vcf.gz}"
  - sage_highconf_regions:
      type: file
      description: SAGE high confidence regions file
      pattern: "*.{bed.gz}"
  - driver_gene_panel:
      type: file
      description: Driver gene panel file
      pattern: "*.{tsv}"
  - ensembl_data_resources:
      type: directory
      description: HMF ensembl data resources directory
  - targeted_mode:
      type: boolean
      description: Flag indicating whether targeted mode is set
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - vcf:
      type: file
      description: SAGE VCF file
      pattern: "*.{vcf.gz}"
  - sage_dir:
      type: directory
      description: SAGE output directory
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - command_files:
      type: list
      description: List of command files
authors:
  - "@scwatts"
