name: teal
description: TEAL measures telomere content, and estimates telomeric length based on WGS read data
keywords:
  - telomere
  - telomere length
  - rearrangements
tools:
  - teal:
      description: TEAL measures telomere content, and estimates telomeric length based on WGS read data.
      homepage: https://github.com/hartwigmedical/hmftools/tree/master/teal
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/teal
      tool_dev_url: https://github.com/hartwigmedical/hmftools/tree/master/teal
      licence: ["GPL v3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - tumor_bam:
      type: file
      description: Tumor BAM file (optional)
      pattern: "*.{bam}"
  - tumor_bai:
      type: file
      description: Tumor BAI file (optional)
      pattern: "*.{bai}"
  - normal_bam:
      type: file
      description: Normal BAM file (optional)
      pattern: "*.{bam}"
  - normal_bai:
      type: file
      description: Normal BAI file (optional)
      pattern: "*.{bai}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample_id']
  - tumor_teal_bam:
      type: list
      description: Tumor TEAL BAM and BAI file
      pattern: "*.{bam,bai}"
  - normal_teal_bam:
      type: list
      description: Normal TEAL BAM and BAI file
      pattern: "*.{bam,bai}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - command_files:
      type: list
      description: List of command files
authors:
  - "@scwatts"
